version: '2'

services:
  wordpress:
    build: .
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: super-secure-password
      WORDPRESS_DEBUG: 1
    volumes:
      - ./src:/var/www/html/wp-content/plugins/linkitwoocommerce
      - /tmp/wordpressuploads:/var/www/html/wp-content/uploads
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: super-secure-password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: super-secure-password
    links:
      - mysql:db
    ports:
      - 8089:80
    volumes:
      - /sessions

